module.exports = {
  user: '/api/v1/user',
  event: '/api/v1/event',
  login: '/api/v1/login',
  register: '/api/v1/register',
  tracking: '/api/v1/tracking',
  attribute: '/api/v1/attribute',
  userAdmin: '/api/v1/user/admin',
  userStatus: '/api/v1/user/status',
  eventEvent: '/api/v1/event/event',
  eventCount: '/api/v1/event/count',
  eventDemand: '/api/v1/event/demand',
  trackingBatch: '/api/v1/tracking/batch',
  trackingDemand: '/api/v1/tracking/demand',
  trackingStatus: '/api/v1/tracking/status',
  trackingVersion: '/api/v1/tracking/version',
}
